version: '3.1'

services:
  dynamo:
    build: .
    ports:
      - 9000:8000
    command:
      -inMemory
  postgres:
    image: postgres:10
    restart: always
    ports:
      - 6543:5432
    environment:
      POSTGRES_PASSWORD: testing
