name: Lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Lint
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8
