name: Type checking

on: push

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Run unit tests
      run: |
        npm install pyright
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        node_modules/.bin/pyright
